services:
  - type: web
    name: hackathon-team-finder-bot
    env: docker
    buildCommand: docker build -t hackathon-bot .
    startCommand: python bot.py
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
    plan: free 